### ISSUE TITLE
Add instrumentation for JS-based font probing

### ISSUE THREAD

**Issue by Helpper** [openwpm/OpenWPM#142]
Now some websites often fingerprint users by detecting fonts. So, I want to know how many fonts that the websites load by counting the access to offsetwidth and offsetHeight properties and getBoundingRect method of HTML elements. Can I do it with OpenWPM? If it can, how should I do?

**Comment by englehardt** [comment]
This should be possible and it would be a great addition to the platform.

You can use the `instrumentObject` function available in the extension instrumentation [here](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/Extension/firefox/data/content.js#L369-L446). You can find examples of how to use this function [here](https://github.com/citp/OpenWPM/blob/a0638550f019e04e91ae926429dc5c33da808b64/automation/Extension/firefox/data/content.js#L614-L641).

So to instrument the properties you've requested it would look something like this (note that I haven't tested this, so there could be some typos):
```javascript
instrumentObject(window.HTMLElement,'HTMLElement', {
    'propertiesToInstrument': [ 'offsetWidth', 'offsetHeight', 'getBoundingRect']
});
```

Take a look at the other options in the `instrumentObject` definition to enable logging of the call stack or logging of functional arguments as strings.

Take a look at the [Development pointers](https://github.com/citp/OpenWPM#development-pointers) section of the README for more info on developing the extension.

**Comment by englehardt** [comment]
Re-opening this as a feature request.

**Comment by Helpper** [comment]
Thank you for your detailed explanation! It helps me a lot!

**Comment by tronje** [comment]
Hi! I'm trying to implement this exact behavior, but without success so far.
I am working on OpenWPM commit `99da2d91897c2ddcb128a0e133cccc09c4f14996`, as I'm trying to patch a version of OpenWPM embedded in a different project, PrivacyScore. So I'm aware it may have something to do with the outdated version, but maybe that's not the case and I'm just missing something.

Anyway, this is what I've tried:

```javascript
instrumentObject(
    window.HTMLElement,
    "HTMLElement",
    {'propertiesToInstrument': ["offsetWidth", "offsetHeight"]}
);
```

I've also tried

```javascript
instrumentObject(
    window.HTMLElement.prototype,
    "HTMLElement",
    {'propertiesToInstrument': ["offsetWidth", "offsetHeight"]}
);
```

Note the `.prototype`. I've also tried using the `HTMLSpanElement` instead of the generic element.

I've crawled a test site with each version, and each time the `javascript` table is empty. JavaScript instrumentation is on, of course.

The site:

```html
<!doctype html>
<html>
    <head></head>
    <body>
    <span id="span_id">hello world</span>
    <script>
        span_elem = document.getElementById("span_id");
        console.log(span_elem.offsetWidth);
        console.log(span_elem.offsetHeight);
    </script>
    </body>
</html>
```

What am I missing? Do I need to make any changes elsewhere in the code?
Or is this indeed because of the older version I am using (though it is newer than this issue)?

Thanks a lot in advance!

**Comment by Helpper** [comment]
@tronje
If you edit the extension, you need to re-build it with jpm.
“python -m test.manual_test --selenium”: This command is to execute manual_test.py, it can help you re-build the new extension. And you can see the detail information in the readme.md
