### ISSUE TITLE
Configure OpenWPM to crawl one single page with all internal links

### ISSUE THREAD

**Issue by 1core0** [openwpm/OpenWPM#956]
I'm spending a couple of days to configure OpenWPM with memcache (first tried it with queue) to crawl one single webpage including all internal links it contains.
Is it somehow possible to easily configure OpenWPM itself without using memcache (saves internal links) and for looping GetCommand?

**Comment by vringar** [comment]
Hey, unfortunately this is not really possible easily.
Since the main program and the commands are running in different processes communicating back from the commands to the main program is a bit tricky.
You could write your own command that finds all internal links and then create a GetCommand on them. However you will run into timeout issues with this. And you won't get the robustness of having multiple CommandSequences.
